version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: infra-mysql
    restart: always
    ports:
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - /Users/happyeon/Desktop/workspace/my_sql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64